import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className="mx-auto xl:container">
      <p className="text-cyan-500">Hello Tailwind ❤️</p>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-[1.5rem]">
        I`m 1.5rem <span className="ml-[15px] text-[41px]">and I`m 41px with 15px margin left</span>
      </p>
      <div className="bg-[#bada55] p-[50px] [color:black] hover:bg-[#123456] hover:[color:white]">
        <h2>Missing utility?</h2>
        <p>Arbitrary properties to the rescue (something like inline CSS)</p>
        <p>Some ne content here</p>
      </div>
      <ul className="mt-3 w-48 rounded-lg border border-gray-200 bg-white text-sm font-medium text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white">
        <li className="relative w-full rounded-t-lg border-b border-gray-200 py-2 px-4 dark:border-gray-600">
          <Link href="/forms">
            <a className="after:absolute after:inset-0">forms</a>
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
