import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import Collapse from 'components/shared/Collapse';
import CustomButton from 'components/shared/CustomButton';
import Dropdown from 'components/shared/dropdown/Dropdown';
import DropdownItem from 'components/shared/dropdown/DropdownItem';
import Modal from 'components/shared/Modal';

const Home: NextPage = () => {
  return (
    <div className="mx-auto xl:container">
      <p className="text-cyan-500">Hello Tailwind ❤️</p>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#bada55] p-[50px] [color:black] hover:bg-[#123456] hover:[color:white]">
        <p className="text-[1.5rem]">
          I`m 1.5rem <span className="ml-[15px] text-[41px]">and I`m 41px with 15px margin left</span>
        </p>
        <p className="text-sm">it`s created with arbitrary properties, something like inline CSS</p>
      </div>
      <ul className="mt-3 w-48 rounded-lg border border-gray-200 bg-white text-sm font-medium text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white">
        <li className="relative w-full rounded-t-lg border-b border-gray-200 py-2 px-4 dark:border-gray-600">
          <Link href="/forms">
            <a className="text-blue-600 after:absolute after:inset-0 hover:text-blue-900">Go to /forms</a>
          </Link>
        </li>
      </ul>
      <div className="mt-3 rounded-lg border border-gray-200 p-3">
        <div className="mb-5 last:mb-0">
          <h2 className="mb-2 text-2xl font-bold">Custom button</h2>
          <CustomButton variant="primary" text="primary" />
          <CustomButton variant="secondary" text="secondary" />
          <CustomButton variant="danger" text="danger" />
          <CustomButton variant="outline" text="outline" />
        </div>
        <div className="mb-5 last:mb-0">
          <h2 className="mb-2 text-2xl font-bold">@headlessUI dropdown component</h2>
          <Dropdown text="Dropdown button">
            <DropdownItem as="button" label="option 1" />
            <DropdownItem as="button" label="option 2" />
            <DropdownItem as="button" label="console.log" onClick={() => console.log('clicked')} />
            <DropdownItem as="link" label="link to /forms" href="/forms" />
          </Dropdown>
        </div>
        <div className="mb-5 last:mb-0">
          <h2 className="mb-2 text-2xl font-bold">@headlessUI disclosure</h2>
          <Collapse text="What is your refund policy?">
            <p>
              If you`re unhappy with your purchase for any reason, email us within 90 days and we`ll refund you in full,
              no questions asked.
            </p>
          </Collapse>
          <Collapse text="I've got defaultOpen set to true" defaultOpen>
            <div className="font-bold text-gray-500">Hello world!</div>
          </Collapse>
        </div>
        <div className="mb-5 last:mb-0">
          <h2 className="mb-2 text-2xl font-bold">@headlessUI modal</h2>
          <Modal buttonText="open dialog">
            <div>
              <h2 className="mb-4 text-xl font-bold">Modal title</h2>
            </div>
            <div>
              <p className="text-md mb-8 text-gray-600">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin viverra velit id tristique rhoncus. Donec
                ultricies laoreet efficitur. Aliquam in elit nec dolor pulvinar egestas quis vitae urna. Class aptent
                taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean in tortor
                malesuada, feugiat orci vitae, ornare diam.
              </p>
            </div>
          </Modal>
        </div>
      </div>
    </div>
  );
};

export default Home;
